import { PlanBoard, UserPersona } from './types';

export const USER_PERSONAS: UserPersona[] = [
  {
    id: 'user-seyi',
    name: 'Seyi',
    displayName: 'Seyi Ayodele',
    username: 'seyi',
    email: 'ayodeleoluwaseyi088@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'owner',
    bio: 'Lead organizer & plan curator. Passionate about bringing friends together for memorable adventures, weekend trips, and milestone celebrations.',
    location: 'Lagos & London',
    memberSince: 'January 2026',
  },
  {
    id: 'user-tobi',
    name: 'Tobi',
    displayName: 'Tobi Adebayo',
    username: 'tobi',
    email: 'tobi@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'admin',
    bio: 'Food connoisseur & weekend explorer. Always hunting down the best dining spots and local group activities.',
    location: 'Lagos, Nigeria',
    memberSince: 'February 2026',
  },
  {
    id: 'user-amaka',
    name: 'Amaka',
    displayName: 'Amaka Eze',
    username: 'amaka',
    email: 'amaka@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'member',
    bio: 'Creative coordinator & music curator. Ensuring playlists are pristine and aesthetic vibes are on point.',
    location: 'Abuja, Nigeria',
    memberSince: 'March 2026',
  },
  {
    id: 'user-kunle',
    name: 'Kunle',
    displayName: 'Kunle Adeleke',
    username: 'kunle',
    email: 'kunle@example.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'member',
    bio: 'Adventure seeker, budget guardian & candid photographer. Keeping the crew organized and on schedule.',
    location: 'Ibadan, Nigeria',
    memberSince: 'April 2026',
  },
];

export interface SuggestedPlanTemplate {
  id: string;
  title: string;
  emoji: string;
  category: string;
  description: string;
  defaultDeciderType: 'voting' | 'fixed_info' | 'task_duty' | 'photo_idea' | 'participant_status';
  defaultVoting?: {
    question: string;
    options: string[];
    deadlineText: string;
  };
  defaultFixedInfo?: {
    value: string;
  };
  defaultTaskDuty?: {
    description: string;
  };
  defaultPhotoIdea?: {
    description: string;
    imageUrl: string;
  };
  defaultParticipantStatus?: {
    question: string;
    options: string[];
  };
}

export const SUGGESTED_PLANS: SuggestedPlanTemplate[] = [
  {
    id: 'sug-plan-attendance',
    title: 'Attendance',
    emoji: '🙋',
    category: 'RSVP & Check-in',
    description: 'Track who will be attending across all joined members with one-click status.',
    defaultDeciderType: 'participant_status',
    defaultParticipantStatus: {
      question: 'Who will be attending?',
      options: ['I will', 'Maybe', 'Not available'],
    },
  },
  {
    id: 'sug-plan-payment',
    title: 'Event Payment',
    emoji: '💳',
    category: 'Budget & Split',
    description: 'Track contributions, ticket splits, or payment status for every joined member.',
    defaultDeciderType: 'participant_status',
    defaultParticipantStatus: {
      question: 'Who has made their payment?',
      options: ['Paid', 'Not yet'],
    },
  },
  {
    id: 'sug-plan-datetime',
    title: 'Date & Time',
    emoji: '📅',
    category: 'Schedule',
    description: 'Set the target date and arrival time, or open a group poll on schedule options.',
    defaultDeciderType: 'fixed_info',
    defaultFixedInfo: {
      value: 'Saturday, August 22, 2026 at 02:00 PM',
    },
    defaultVoting: {
      question: 'Which date and time works best for everyone?',
      options: ['Saturday, August 22, 2026 (2:00 PM)', 'Sunday, August 23, 2026 (1:00 PM)', 'Following Saturday (Aug 29)'],
      deadlineText: 'Voting closes this Wednesday',
    },
  },
  {
    id: 'sug-plan-location',
    title: 'Location',
    emoji: '📍',
    category: 'Location',
    description: 'Decide where everyone meets or where the main event happens.',
    defaultDeciderType: 'photo_idea',
    defaultPhotoIdea: {
      description: 'Submit photos or ideas for the venue, cabana, or beach lounge.',
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    },
    defaultVoting: {
      question: 'Which location do you prefer for the gathering?',
      options: ['Landmark Beach Private Cabana', 'Tarkwa Bay Shoreline', 'Elegushi Private Lounge'],
      deadlineText: 'Voting closes in 2 days',
    },
  },
  {
    id: 'sug-plan-drinks',
    title: 'Drinks',
    emoji: '🥤',
    category: 'Drinks',
    description: 'Stock the cooler, choose beverages, or set BYOB ground rules.',
    defaultDeciderType: 'voting',
    defaultVoting: {
      question: 'What drinks should we stock in the group cooler?',
      options: ['Coke & Assorted Sodas', 'Fanta & Fruit Juices', 'Cold Malt & Energy Drinks'],
      deadlineText: 'Voting closes tomorrow at 8:00 PM',
    },
    defaultFixedInfo: {
      value: 'Everyone should bring their preferred drinks or bottle to share.',
    },
  },
  {
    id: 'sug-plan-music',
    title: 'Music',
    emoji: '🎵',
    category: 'Music',
    description: 'Sound equipment, DJ coordination, and shared party playlist.',
    defaultDeciderType: 'task_duty',
    defaultTaskDuty: {
      description: 'Bring high-power party speaker, AUX cables, and coordinate DJ playlist.',
    },
    defaultVoting: {
      question: 'What genre vibe should dominate the party?',
      options: ['Afrobeats & Amapiano', 'Throwback 90s/2000s Hits', 'Chill House & Sunset Vibes'],
      deadlineText: 'Voting closes Friday 6:00 PM',
    },
  },
  {
    id: 'sug-plan-food',
    title: 'Food',
    emoji: '🍔',
    category: 'Food',
    description: 'Catering, barbecue grill, party chops, and feast menu.',
    defaultDeciderType: 'voting',
    defaultVoting: {
      question: 'What should we order for lunch catering?',
      options: ['Grilled Chicken & Yam/Potato Chips', 'Woodfired Party Pizzas', 'Creamy Seafood Pasta'],
      deadlineText: 'Voting closes Friday 6:00 PM',
    },
    defaultFixedInfo: {
      value: 'Catering ordered: BBQ Chicken, Jollof Rice, and Small Chops pack for all.',
    },
  },
  {
    id: 'sug-plan-theme',
    title: 'Theme',
    emoji: '🎨',
    category: 'Theme',
    description: 'Dress code, visual style, and color coordination for photos.',
    defaultDeciderType: 'fixed_info',
    defaultFixedInfo: {
      value: 'Dress Code: Summer Whites & Floral Prints (Beachwear ready).',
    },
    defaultPhotoIdea: {
      description: 'Drop aesthetic moodboard photos for outfit inspiration.',
      imageUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'sug-plan-gift',
    title: 'Gift',
    emoji: '🎁',
    category: 'Gift',
    description: 'Group surprise gift, envelope, or birthday token.',
    defaultDeciderType: 'task_duty',
    defaultTaskDuty: {
      description: 'Collect joint gift funds, buy the curated gift box, and prepare the card.',
    },
    defaultVoting: {
      question: 'Which gift idea should we pool together for?',
      options: ['Apple Watch Series 9', 'Weekend Spa & Massage Voucher', 'Surprise Custom Portrait'],
      deadlineText: 'Closes Friday 5:00 PM',
    },
  },
  {
    id: 'sug-plan-transport',
    title: 'Transportation',
    emoji: '🚗',
    category: 'Transportation',
    description: 'Carpooling, bus charter, or convoy meeting points.',
    defaultDeciderType: 'task_duty',
    defaultTaskDuty: {
      description: 'Arrange 18-seater coaster bus pickup from central terminal and manage convoy.',
    },
    defaultFixedInfo: {
      value: 'Coaster bus departs from Wuse 2 Total Station sharp at 10:00 AM.',
    },
  },
  {
    id: 'sug-plan-decoration',
    title: 'Decoration',
    emoji: '🎈',
    category: 'Decoration',
    description: 'Balloons, signage, cabana setup, and photo backdrop.',
    defaultDeciderType: 'photo_idea',
    defaultPhotoIdea: {
      description: 'Submit decoration ideas, balloon arch references, or table setups.',
      imageUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&auto=format&fit=crop&q=80',
    },
    defaultTaskDuty: {
      description: 'Buy custom 26 balloon arch and set up cabana ribbons before guests arrive.',
    },
  },
  {
    id: 'sug-plan-cake',
    title: 'Cake',
    emoji: '🎂',
    category: 'Cake',
    description: 'Celebration cake flavor, bakery ordering, and delivery.',
    defaultDeciderType: 'voting',
    defaultVoting: {
      question: 'Which birthday cake flavor should we order?',
      options: ['Red Velvet with Cream Cheese', 'Dark Belgian Chocolate Ganache', 'Vanilla Berry Sponge'],
      deadlineText: 'Voting closes in 2 days',
    },
  },
  {
    id: 'sug-plan-photo',
    title: 'Photography',
    emoji: '📸',
    category: 'Photography',
    description: 'Capturing memories, drone footage, and instant polaroids.',
    defaultDeciderType: 'task_duty',
    defaultTaskDuty: {
      description: 'Bring polaroid camera + 4 film packs and manage group photo shots.',
    },
  },
  {
    id: 'sug-plan-games',
    title: 'Games',
    emoji: '🎮',
    category: 'Games',
    description: 'Beach volleyball, trivia questions, drinking games, and cards.',
    defaultDeciderType: 'task_duty',
    defaultTaskDuty: {
      description: 'Bring Cards Against Humanity, beach volleyball, and curate 3 trivia rounds.',
    },
  },
  {
    id: 'sug-plan-accommodation',
    title: 'Accommodation',
    emoji: '🏨',
    category: 'Accommodation',
    description: 'Overnight chalet, beach cabana reservation, or hotel blocks.',
    defaultDeciderType: 'fixed_info',
    defaultFixedInfo: {
      value: 'Landmark Beach Private Beachfront Cabana #4 reserved from 12:00 PM to 8:00 PM.',
    },
  },
];

export const TEMPLATE_PLANS = [
  {
    id: 'template-beach',
    title: 'Beach Day & Private Cabana',
    emoji: '🏖️',
    category: 'Main Event',
    deciderType: 'photo_idea' as const,
    description: 'Private cabana rental with volleyball, catering, DJ music and beach games.',
    location: 'Landmark Beach Private Cabana #4',
    time: '12:00 PM - 06:00 PM',
    estimatedCost: '₦8,500 / person',
    status: 'confirmed' as const,
  },
  {
    id: 'template-afterparty',
    title: 'Rooftop Sunset Lounge & Drinks',
    emoji: '🥂',
    category: 'Evening Afterparty',
    deciderType: 'voting' as const,
    description: 'Post-event sunset cocktails, skyline views, and celebration toast.',
    location: 'Skylight Rooftop Lounge & Bar',
    time: '07:30 PM - Late',
    estimatedCost: 'Pay as you order',
    status: 'active' as const,
  },
];

export const INITIAL_BOARD: PlanBoard = {
  id: 'board-biggi-birthday',
  title: "Biggi Birthday",
  emoji: '💵',
  coverImage: 'https://images.unsplash.com/photo-1543807535-eceef0bc6599?w=1600&auto=format&fit=crop&q=80',
  dateTime: '2026-12-12T19:00:00',
  date: 'Sat 12 Dec',
  time: '7:PM',
  hasSpecificTime: true,
  daysToGo: 4,
  state: 'almost_ready',
  ownerId: 'user-seyi',
  ownerName: 'Seyi',
  description: 'Guys, celebrating Biggi Birthday with great drinks, music and vibes. Let us build the plan together!',
  
  // Attached Plans on this Board - each with its Decider Type and content
  plans: [
    {
      id: 'plan-location',
      title: 'Location',
      emoji: '📍',
      category: 'Location',
      deciderType: 'photo_idea',
      deciderItemId: 'dec-location',
      dateTime: '2026-12-12T19:00:00',
      date: 'Sat 12 Dec',
      time: '7:PM',
      hasSpecificTime: true,
      description: 'Private cabana rental at Landmark Beach with volleyball, catering, and beach games.',
      ideaDesc: 'Great sunset views, private cabana space, volleyball court, and safe swimming area.',
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
      heartCount: 7,
      isSelectedWinner: true,
      initialSelection: 'Landmark Beach Private Cabana #4',
      currentSelection: 'Landmark Beach Private Cabana #4',
      location: 'Landmark Beach Private Cabana #4',
      status: 'confirmed',
      priority: 'required',
      isPrimary: true,
      appliedSuggestionId: 'sug-landmark',
      previousPlanSnapshot: {
        currentSelection: 'Landmark Beach (General Area)',
        location: 'Landmark Beach (General Area)',
        initialSelection: 'Landmark Beach (General Area)',
        status: 'active',
        isSelectedWinner: false,
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
        description: 'Private cabana rental at Landmark Beach with volleyball, catering, and beach games.',
      },
    },
    {
      id: 'plan-drinks',
      title: 'Drinks',
      emoji: '🥤',
      category: 'Drinks',
      deciderType: 'voting',
      deciderItemId: 'dec-drinks',
      description: 'Decide what drinks to stock in the beach cooler for everyone.',
      question: 'What should we get for the beach cooler?',
      deadlineText: 'Closes tomorrow at 8:00 PM',
      totalVotesNeeded: 12,
      initialSelection: 'Coke & Sodas',
      currentSelection: 'Coke & Sodas',
      status: 'active',
      priority: 'required',
    },
    {
      id: 'plan-food',
      title: 'Food & Catering',
      emoji: '🍔',
      category: 'Food',
      deciderType: 'voting',
      deciderItemId: 'dec-food',
      description: 'Group majority vote on beach lunch catering feast.',
      question: 'What should we order for lunch?',
      initialSelection: 'Grilled Chicken & Yam/Potato Chips',
      currentSelection: 'Grilled Chicken & Yam/Potato Chips',
      finalDecision: 'Grilled Chicken & Chips ✓ (Group decision)',
      deadlineText: 'Finalized by group majority',
      status: 'confirmed',
      priority: 'required',
    },
    {
      id: 'plan-cake',
      title: 'Birthday Cake',
      emoji: '🎂',
      category: 'Cake',
      deciderType: 'voting',
      deciderItemId: 'dec-cake',
      description: 'Choose between red velvet and Belgian chocolate ganache.',
      question: 'Red velvet or Belgian chocolate ganache?',
      deadlineText: 'Voting closes in 2 days',
      totalVotesNeeded: 12,
      initialSelection: 'Red Velvet with Cream Cheese',
      currentSelection: 'Red Velvet with Cream Cheese',
      status: 'active',
      priority: 'important',
    },
    {
      id: 'plan-music',
      title: 'Music & DJ',
      emoji: '🎵',
      category: 'Music',
      deciderType: 'task_duty',
      deciderItemId: 'task-speaker',
      description: 'Sound equipment, party speaker, and music playlist coordination.',
      taskDesc: 'Bring high-power JBL party box, aux cord, and coordinate Afrobeats playlist.',
      assigneeName: 'Tobi',
      assigneeId: 'user-tobi',
      initialSelection: 'Tobi (DJ & Speaker Coordination)',
      currentSelection: 'Tobi (DJ & Speaker Coordination)',
      status: 'confirmed',
      priority: 'required',
    },
    {
      id: 'plan-transport',
      title: 'Transportation',
      emoji: '🚗',
      category: 'Transportation',
      deciderType: 'task_duty',
      deciderItemId: 'task-transport',
      dateTime: '2026-09-19T10:00:00',
      date: 'September 19, 2026',
      time: '10:00 AM',
      hasSpecificTime: true,
      description: 'Van rental and group convoy coordination.',
      taskDesc: 'Confirm driver, fuel, and coordinate 18-seater Coaster bus pickup from Wuse 2.',
      assigneeName: 'Kunle',
      assigneeId: 'user-kunle',
      initialSelection: '18-seater Coaster bus pickup from Wuse 2',
      currentSelection: '18-seater Coaster bus pickup from Wuse 2',
      status: 'active',
      priority: 'important',
    },
    {
      id: 'plan-attendance',
      title: 'Attendance',
      emoji: '🙋',
      category: 'RSVP & Check-in',
      deciderType: 'participant_status',
      description: 'Check-in status for everyone who joined this board.',
      statusQuestion: 'Who will be attending?',
      statusOptions: [
        { id: 'opt-attending', label: 'Attending', emoji: '✅', color: 'emerald' },
        { id: 'opt-maybe', label: 'Maybe', emoji: '🤔', color: 'amber' },
        { id: 'opt-unavailable', label: 'Not Attending', emoji: '❌', color: 'rose' },
      ],
      participantStatuses: {
        'user-seyi': { userId: 'user-seyi', userName: 'Seyi', userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', statusOptionId: 'opt-attending', statusLabel: 'Attending', updatedAt: 'Today' },
        'user-amaka': { userId: 'user-amaka', userName: 'Amaka', userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', statusOptionId: 'opt-attending', statusLabel: 'Attending', updatedAt: 'Today' },
        'user-tobi': { userId: 'user-tobi', userName: 'Tobi', userAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80', statusOptionId: 'opt-attending', statusLabel: 'Attending', updatedAt: 'Yesterday' },
        'user-kunle': { userId: 'user-kunle', userName: 'Kunle', userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80', statusOptionId: 'opt-maybe', statusLabel: 'Maybe', updatedAt: '2 days ago' },
        'user-chioma': { userId: 'user-chioma', userName: 'Chioma', userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80', statusOptionId: 'opt-attending', statusLabel: 'Attending', updatedAt: 'Yesterday' },
      },
      currentSelection: '4 attending · 1 maybe',
      status: 'active',
      priority: 'required',
    },
    {
      id: 'plan-meeting',
      title: 'Meeting Point',
      emoji: '📍',
      category: 'Meeting Point',
      deciderType: 'fixed_info',
      deciderItemId: 'info-meeting',
      description: 'Arrival location and entry gate instructions.',
      infoValue: 'Landmark Beach Gate 3 (Main Entrance) at 10:00 AM sharp.',
      fixedBy: 'Seyi',
      initialSelection: 'Landmark Beach Gate 3 (Main Entrance) at 10:00 AM sharp.',
      currentSelection: 'Landmark Beach Gate 3 (Main Entrance) at 10:00 AM sharp.',
      status: 'confirmed',
      priority: 'required',
    },
    {
      id: 'plan-dress',
      title: 'Theme & Dress Code',
      emoji: '🎨',
      category: 'Theme',
      deciderType: 'fixed_info',
      deciderItemId: 'info-dress',
      description: 'Ground rule styling for the day.',
      infoValue: 'Summer Whites & Floral prints (Beachwear ready).',
      fixedBy: 'Seyi',
      initialSelection: 'Summer Whites & Floral prints (Beachwear ready).',
      currentSelection: 'Summer Whites & Floral prints (Beachwear ready).',
      status: 'confirmed',
      priority: 'important',
    },
    {
      id: 'plan-food-blindpick',
      title: 'Food',
      emoji: '🍹',
      category: 'Food & Dining',
      deciderType: 'blind_pick',
      description: 'Draw a mystery card to choose our food!',
      spinnerQuestion: 'What should we choose for Food?',
      spinnerOptions: [
        'KFC',
        'Chicken Republic',
        'Kilimanjaro',
        'The Place',
        "Domino's",
      ],
      status: 'active',
      priority: 'important',
    },
    {
      id: 'plan-dinner-wheel',
      title: 'Where Should We Eat?',
      emoji: '🎡',
      category: 'Food & Dining',
      deciderType: 'wheel_spinner',
      description: 'Spin the wheel to make a fun, spontaneous group decision for dinner!',
      spinnerQuestion: 'Where should we eat?',
      spinnerOptions: [
        'KFC',
        'Chicken Republic',
        'Kilimanjaro',
        'The Place',
        "Domino's",
      ],
      status: 'active',
      priority: 'important',
    },
    {
      id: 'plan-party-game-blindpick',
      title: 'After-Dinner Party Game',
      emoji: '🎴',
      category: 'Activities & Fun',
      deciderType: 'blind_pick',
      description: 'Draw a mystery card to pick tonight’s group party game!',
      spinnerQuestion: 'Which game are we playing tonight?',
      spinnerOptions: [
        'Karaoke Showdown',
        'Charades / Heads Up',
        'Trivia Challenge',
        'Never Have I Ever',
        'Card Game Blitz',
      ],
      status: 'active',
      priority: 'optional',
    },
  ],

  members: [
    {
      id: 'user-seyi',
      name: 'Seyi',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      role: 'owner',
      responsibility: 'Host & Overall Coordinator',
    },
    {
      id: 'user-tobi',
      name: 'Tobi',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      role: 'admin',
      responsibility: 'Sound system & DJ Coordination',
    },
    {
      id: 'user-amaka',
      name: 'Amaka',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      role: 'member',
      responsibility: 'Beachside Decorations & Balloons',
    },
    {
      id: 'user-kunle',
      name: 'Kunle',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      role: 'member',
      responsibility: 'Van & Group Transportation',
    },
    {
      id: 'user-fatima',
      name: 'Fatima',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      role: 'member',
      responsibility: 'Games & Icebreakers',
    },
    {
      id: 'user-chinedu',
      name: 'Chinedu',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
      role: 'member',
    },
    {
      id: 'user-bola',
      name: 'Bola',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      role: 'member',
    },
    {
      id: 'user-emeka',
      name: 'Emeka',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      role: 'member',
    },
    {
      id: 'user-zainab',
      name: 'Zainab',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      role: 'member',
    },
    {
      id: 'user-dayo',
      name: 'Dayo',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      role: 'member',
    },
    {
      id: 'user-kemi',
      name: 'Kemi',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      role: 'member',
    },
    {
      id: 'user-femi',
      name: 'Femi',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      role: 'member',
    },
  ],

  // 1. Decisions / Polls
  decisions: [
    {
      id: 'dec-location',
      type: 'decision',
      planId: 'plan-location',
      deciderItemId: 'plan-location',
      title: 'Location Selection',
      category: '📍 LOCATION',
      question: 'Which venue should we lock in for the gathering?',
      options: [
        {
          id: 'opt-loc-landmark',
          label: 'Landmark Beach Private Cabana #4',
          emoji: '🏖️',
          voteCount: 5,
          voterIds: ['user-seyi', 'user-amaka', 'user-fatima', 'user-chinedu', 'user-bola'],
        },
        {
          id: 'opt-loc-rooftop',
          label: 'Skylight Rooftop Restaurant Lounge',
          emoji: '🌆',
          voteCount: 4,
          voterIds: ['user-tobi', 'user-kunle', 'user-dayo', 'user-zainab'],
        },
        {
          id: 'opt-loc-tarkwa',
          label: 'Tarkwa Bay Beachfront Shack',
          emoji: '🏝️',
          voteCount: 2,
          voterIds: ['user-emeka', 'user-kemi'],
        },
      ],
      totalVotesNeeded: 12,
      deadlineText: 'Voting closes Friday 6:00 PM',
      priority: 'required',
      status: 'open',
      gamifiedNote: 'Landmark Beach Cabana is currently in the lead! 🏖️',
      createdBy: 'user-seyi',
    },
    {
      id: 'dec-drinks',
      type: 'decision',
      planId: 'plan-drinks',
      deciderItemId: 'plan-drinks',
      title: 'Drinks Selection',
      category: '🥤 DRINKS',
      question: 'What should we get for the beach cooler?',
      options: [
        {
          id: 'opt-coke',
          label: 'Coke & Sodas',
          emoji: '🥤',
          voteCount: 5,
          voterIds: ['user-seyi', 'user-tobi', 'user-fatima', 'user-chinedu', 'user-bola'],
        },
        {
          id: 'opt-fanta',
          label: 'Fanta Orange',
          emoji: '🍊',
          voteCount: 3,
          voterIds: ['user-emeka', 'user-zainab', 'user-dayo'],
        },
        {
          id: 'opt-malt',
          label: 'Cold Malt & Juices',
          emoji: '🥛',
          voteCount: 2,
          voterIds: ['user-kemi', 'user-femi'],
        },
      ],
      totalVotesNeeded: 12,
      deadlineText: 'Closes tomorrow at 8:00 PM',
      priority: 'required',
      status: 'open',
      gamifiedNote: 'Coke is currently winning 👀 Fanta team, you need 2 more votes!',
      createdBy: 'user-seyi',
    },
    {
      id: 'dec-food',
      type: 'decision',
      planId: 'plan-food',
      deciderItemId: 'plan-food',
      title: 'Lunch Catering',
      category: '🍗 FOOD',
      question: 'What should we order for lunch?',
      options: [
        {
          id: 'opt-chicken-chips',
          label: 'Grilled Chicken & Yam/Potato Chips',
          emoji: '🍗',
          voteCount: 7,
          voterIds: ['user-seyi', 'user-tobi', 'user-amaka', 'user-kunle', 'user-fatima', 'user-chinedu', 'user-bola'],
        },
        {
          id: 'opt-pizza',
          label: 'Woodfired Party Pizzas',
          emoji: '🍕',
          voteCount: 3,
          voterIds: ['user-emeka', 'user-zainab', 'user-dayo'],
        },
        {
          id: 'opt-pasta',
          label: 'Creamy Seafood Pasta',
          emoji: '🍝',
          voteCount: 1,
          voterIds: ['user-kemi'],
        },
      ],
      totalVotesNeeded: 12,
      deadlineText: 'Finalized by group majority',
      priority: 'required',
      status: 'completed',
      finalDecision: 'Grilled Chicken & Chips ✓ (Group decision)',
      createdBy: 'user-seyi',
    },
    {
      id: 'dec-cake',
      type: 'decision',
      planId: 'plan-cake',
      deciderItemId: 'plan-cake',
      title: 'Birthday Cake Flavor',
      category: '🎂 CAKE',
      question: 'Red velvet or Belgian chocolate ganache?',
      options: [
        {
          id: 'opt-redvelvet',
          label: 'Red Velvet with Cream Cheese',
          emoji: '🍰',
          voteCount: 6,
          voterIds: ['user-seyi', 'user-amaka', 'user-fatima', 'user-bola', 'user-zainab', 'user-kemi'],
        },
        {
          id: 'opt-chocolate',
          label: 'Dark Belgian Chocolate',
          emoji: '🍫',
          voteCount: 4,
          voterIds: ['user-tobi', 'user-kunle', 'user-chinedu', 'user-dayo'],
        },
      ],
      totalVotesNeeded: 12,
      deadlineText: 'Voting closes in 2 days',
      priority: 'important',
      status: 'open',
      gamifiedNote: 'Red Velvet is in the lead by 2 votes! 🍰',
      createdBy: 'user-amaka',
    },
  ],

  // 2. Visual Suggestions (Locked to specific plans)
  suggestions: [
    {
      id: 'sug-landmark',
      type: 'suggestion',
      title: 'Landmark Beach Private Cabana',
      category: '📍 Location',
      description: 'Shaded cabana right near the water, boardwalk access, volleyball space, and sunset view.',
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
      authorId: 'user-amaka',
      authorName: 'Amaka',
      heartCount: 24,
      heartedByMemberIds: ['user-seyi', 'user-tobi', 'user-amaka', 'user-kunle', 'user-fatima', 'user-chinedu', 'user-bola'],
      isSelectedWinner: true,
      status: 'fixed',
      priority: 'required',
      planId: 'plan-location',
      planTitle: 'Location',
      planEmoji: '📍',
      isPutUpForVote: false,
    },
    {
      id: 'sug-rooftop',
      type: 'suggestion',
      title: 'Skylight Rooftop Restaurant Lounge',
      category: '📍 Location',
      description: 'Stunning city skyline view, infinity pool vibe, gourmet finger food and ambient lighting.',
      imageUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&auto=format&fit=crop&q=80',
      authorId: 'user-kunle',
      authorName: 'Kunle',
      heartCount: 18,
      heartedByMemberIds: ['user-emeka', 'user-zainab', 'user-dayo', 'user-kemi'],
      isSelectedWinner: false,
      status: 'open',
      priority: 'required',
      planId: 'plan-location',
      planTitle: 'Location',
      planEmoji: '📍',
      isPutUpForVote: true,
    },
    {
      id: 'sug-tarkwa',
      type: 'suggestion',
      title: 'Tarkwa Bay Beachfront Shack',
      category: '📍 Location',
      description: 'Boat ride across the lagoon, serene waves, coconut palms, and peaceful private beach strip.',
      imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&auto=format&fit=crop&q=80',
      authorId: 'user-tobi',
      authorName: 'Tobi',
      heartCount: 7,
      heartedByMemberIds: ['user-femi', 'user-chinedu'],
      isSelectedWinner: false,
      status: 'open',
      priority: 'required',
      planId: 'plan-location',
      planTitle: 'Location',
      planEmoji: '📍',
      isPutUpForVote: false,
    },
    {
      id: 'sug-music-sunset',
      type: 'suggestion',
      title: 'Amapiano & Afrobeats Sunset DJ Set',
      category: '🎵 Music & DJ',
      description: 'High-energy Afrobeats, Asake, Burna Boy, and chill Amapiano sunset transition vibes.',
      imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80',
      authorId: 'user-tobi',
      authorName: 'Tobi',
      heartCount: 31,
      heartedByMemberIds: ['user-seyi', 'user-tobi', 'user-amaka', 'user-kunle', 'user-fatima'],
      isSelectedWinner: true,
      status: 'fixed',
      priority: 'required',
      planId: 'plan-music',
      planTitle: 'Music & DJ',
      planEmoji: '🎵',
      isPutUpForVote: false,
    },
    {
      id: 'sug-music-rnb',
      type: 'suggestion',
      title: '90s R&B & Throwback Singalong Session',
      category: '🎵 Music & DJ',
      description: 'Nostalgic 90s/2000s R&B classics for when everyone is chilling around the cabana.',
      imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
      authorId: 'user-fatima',
      authorName: 'Fatima',
      heartCount: 14,
      heartedByMemberIds: ['user-fatima', 'user-zainab'],
      isSelectedWinner: false,
      status: 'open',
      priority: 'important',
      planId: 'plan-music',
      planTitle: 'Music & DJ',
      planEmoji: '🎵',
      isPutUpForVote: true,
    },
    {
      id: 'sug-theme-linen',
      type: 'suggestion',
      title: 'All-White Linen & Pastel Beach Aesthetic',
      category: '🎨 Theme & Dress Code',
      description: 'Breathable linen shirts, white shorts, pastel sun hats, and classy sunglasses photo-op.',
      imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80',
      images: [
        {
          id: 'img-linen-1',
          url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80',
          title: 'Linen Pastel Look',
        },
        {
          id: 'img-linen-2',
          url: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&auto=format&fit=crop&q=80',
          title: 'Beach Picnic Style',
        },
        {
          id: 'img-linen-3',
          url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
          title: 'Sunset Beachwear',
        },
      ],
      authorId: 'user-amaka',
      authorName: 'Amaka',
      heartCount: 19,
      heartedByMemberIds: ['user-amaka', 'user-seyi', 'user-bola'],
      isSelectedWinner: false,
      status: 'open',
      priority: 'important',
      planId: 'plan-dress',
      planTitle: 'Theme & Dress Code',
      planEmoji: '🎨',
      isPutUpForVote: false,
      link: 'https://pinterest.com/pin/beach-linen-aesthetic',
    },
    {
      id: 'sug-theme-tropical',
      type: 'suggestion',
      title: 'Tropical Hawaiian & Floral Patterns',
      category: '🎨 Theme & Dress Code',
      description: 'Bright tropical floral shirts, vibrant colors, and festival-style beach leis.',
      imageUrl: 'https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=800&auto=format&fit=crop&q=80',
      authorId: 'user-chinedu',
      authorName: 'Chinedu',
      heartCount: 8,
      heartedByMemberIds: ['user-chinedu', 'user-dayo'],
      isSelectedWinner: false,
      status: 'open',
      priority: 'optional',
      planId: 'plan-dress',
      planTitle: 'Theme & Dress Code',
      planEmoji: '🎨',
      isPutUpForVote: false,
    },
  ],

  // 3. Tasks / Responsibilities
  tasks: [
    {
      id: 'task-speaker',
      type: 'task',
      planId: 'plan-music',
      deciderItemId: 'plan-music',
      title: 'JBL Boombox & DJ playlist setup',
      category: '🎵 MUSIC',
      description: 'Bring the heavy battery-powered bluetooth speaker and loaded Afrobeats/Amapiano playlist.',
      assigneeId: 'user-tobi',
      assigneeName: 'Tobi',
      status: 'completed',
      priority: 'required',
      deadlineText: 'Done ✓',
    },
    {
      id: 'task-transport',
      type: 'task',
      planId: 'plan-transport',
      deciderItemId: 'plan-transport',
      title: '14-Seater Coaster Bus Charter',
      category: '🚗 TRANSPORTATION',
      description: 'Charter bus from Wuse 2 rendezvous point to Landmark Beach and return trip at 6 PM.',
      assigneeId: 'user-kunle',
      assigneeName: 'Kunle',
      status: 'in_progress',
      priority: 'required',
      deadlineText: 'Bus driver confirmed, collecting pickup roster',
    },
    {
      id: 'task-decorations',
      type: 'task',
      title: 'Beach Cabana Balloons & Custom Banner',
      category: '🎈 DECOR',
      description: 'Custom "Seyi @ 26" banner, photo props, gold & white balloons.',
      assigneeId: 'user-amaka',
      assigneeName: 'Amaka',
      status: 'in_progress',
      priority: 'important',
      deadlineText: 'Printing tomorrow',
    },
    {
      id: 'task-icebreakers',
      type: 'task',
      title: 'Beach Volleyball & Trivia Cards',
      category: '🎯 ACTIVITIES',
      description: 'Bring volleyball, card games, and trivia about Seyi.',
      assigneeId: 'user-fatima',
      assigneeName: 'Fatima',
      status: 'completed',
      priority: 'optional',
      deadlineText: 'Packed in tote bag ✓',
    },
    {
      id: 'task-cooler',
      type: 'task',
      title: 'Heavy Duty Ice Coolers & Ice Blocks',
      category: '🧊 REFRESHMENTS',
      description: 'Need someone with a pickup car to bring 2 large Coleman coolers with ice.',
      priority: 'important',
      status: 'open',
      deadlineText: 'Looking for 1 volunteer!',
    },
  ],

  // 4. Contributions (Money, materials, etc.)
  contributions: [
    {
      id: 'contrib-food-drinks',
      type: 'contribution',
      title: 'Beach Pass & Lunch Pool',
      category: '💰 PAYMENT',
      targetAmount: 102000,
      currentAmount: 76500,
      currency: '₦',
      contributorsPaid: [
        'user-seyi',
        'user-tobi',
        'user-amaka',
        'user-kunle',
        'user-fatima',
        'user-chinedu',
        'user-bola',
        'user-emeka',
        'user-zainab',
      ],
      totalContributorsNeeded: 12,
      status: 'in_progress',
      priority: 'required',
      deadlineText: 'Due in 2 days (₦8,500/person)',
    },
  ],

  // 5. Information (Fixed truth)
  information: [
    {
      id: 'info-date',
      type: 'information',
      title: 'Event Date & Time',
      category: '📅 DATE',
      value: 'Saturday, September 19 · 12:00 PM',
      fixedBy: 'Seyi',
      status: 'fixed',
      priority: 'required',
    },
    {
      id: 'info-meeting',
      type: 'information',
      planId: 'plan-meeting',
      deciderItemId: 'plan-meeting',
      title: 'Central Meeting Point',
      category: '📍 MEETING POINT',
      value: 'Central Park Gate 3 (Wuse 2) at 10:00 AM sharp',
      fixedBy: 'Kunle',
      status: 'fixed',
      priority: 'required',
    },
    {
      id: 'info-dress',
      type: 'information',
      planId: 'plan-dress',
      deciderItemId: 'plan-dress',
      title: 'Dress Code',
      category: '👔 DRESS CODE',
      value: 'All-White or Tropical Chic (sunglasses & beach footwear recommended)',
      fixedBy: 'Seyi',
      status: 'fixed',
      priority: 'important',
    },
    {
      id: 'info-budget',
      type: 'information',
      title: 'Individual Budget',
      category: '🏷️ ESTIMATED COST',
      value: '₦8,500 per person (covers entry pass, beach food, drinks & bus)',
      fixedBy: 'Seyi',
      status: 'fixed',
      priority: 'important',
    },
  ],

  // 6. Timeline
  timeline: [
    {
      id: 'tl-1',
      time: '10:00 AM',
      title: 'Meet at Central Park Wuse 2',
      location: 'Gate 3 parking lot',
      details: 'Pack coolers, board chartered coaster bus',
    },
    {
      id: 'tl-2',
      time: '11:00 AM',
      title: 'Bus Departure',
      details: 'Playlist pumping, route convoy',
    },
    {
      id: 'tl-3',
      time: '12:00 PM',
      title: 'Arrive at Landmark Beach',
      location: 'Beachfront Cabana #4',
      details: 'Check-in through VIP group gate, set up sound & banner',
    },
    {
      id: 'tl-4',
      time: '01:00 PM',
      title: 'Grilled Lunch & Toast to Seyi',
      details: 'Chicken & chips served, cold drinks popped',
    },
    {
      id: 'tl-5',
      time: '03:00 PM',
      title: 'Beach Volleyball & Sunset Jam',
      details: 'Tournament, photos, cake cutting with Amaka & Fatima',
    },
    {
      id: 'tl-6',
      time: '06:00 PM',
      title: 'Wrap Up & Bus Return',
      details: 'Pack up, return trip to central drop-off',
    },
  ],

  // 7. Recent Activity (Lightweight moments, not chat)
  recentActivities: [
    {
      id: 'act-1',
      actorName: 'Seyi',
      actorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      actionText: 'selected Landmark Beach as official location ✓',
      timeAgo: '2h ago',
      badgeEmoji: '📍',
    },
    {
      id: 'act-2',
      actorName: 'Kunle',
      actorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      actionText: 'volunteered for 14-seater charter transportation 🚐',
      timeAgo: '4h ago',
      badgeEmoji: '🚐',
    },
    {
      id: 'act-3',
      actorName: 'Tobi',
      actorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      actionText: 'voted for Coke & Sodas 🥤',
      timeAgo: '5h ago',
      badgeEmoji: '🥤',
    },
    {
      id: 'act-4',
      actorName: 'Amaka',
      actorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      actionText: 'suggested Landmark Beach Private Cabana with photos 📸',
      timeAgo: '8h ago',
      badgeEmoji: '📸',
    },
    {
      id: 'act-5',
      actorName: 'Fatima',
      actorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      actionText: 'completed Beach Volleyball & Trivia Cards task ✓',
      timeAgo: '1d ago',
      badgeEmoji: '🎯',
    },
  ],
};

// Evolution snapshots: demonstrate Day 1 -> Day 3 -> Day 5 (Plan Ready!)
export const EVOLUTION_PRESETS = {
  day1: {
    label: 'Day 1: Idea Spark',
    tag: 'Early Planning',
    description: 'Only date selected. Everything else open for suggestions.',
    readinessText: '2/8 essential things ready',
    readinessPercent: 25,
  },
  day3: {
    label: 'Day 3: Group Contributing',
    tag: 'High Activity',
    description: 'Location picked, votes pouring in for drinks & food, responsibilities claimed.',
    readinessText: '6/8 essential things ready',
    readinessPercent: 75,
  },
  day5: {
    label: 'Day 5: Plan Ready 🎉',
    tag: 'Locked In',
    description: 'All decisions finalized, payments collected, bus locked, ready to celebrate!',
    readinessText: '8/8 essential things ready (100%)',
    readinessPercent: 100,
  },
};

export const OTHER_BOARDS: Partial<PlanBoard>[] = [
  {
    id: 'board-seyis-birthday',
    title: "Seyi's Birthday",
    emoji: '🎂',
    date: 'Sept 19, 2026',
    time: '12:00 PM',
    daysToGo: 4,
    state: 'almost_ready',
    ownerName: 'Seyi',
    description: 'Landmark Beach celebration with 12 friends.',
    plans: [
      {
        id: 'plan-sb-1',
        title: 'Beach Day & Private Cabana',
        emoji: '🏖️',
        category: 'Main Event',
        deciderType: 'fixed_info',
        description: 'Private cabana rental at Landmark Beach with volleyball, catering, DJ music and beach games.',
        location: 'Landmark Beach Private Cabana #4',
        time: '12:00 PM - 06:00 PM',
        estimatedCost: '₦8,500 / person',
        status: 'confirmed',
        isPrimary: true,
      },
      {
        id: 'plan-sb-2',
        title: 'Rooftop Sunset Lounge & Drinks',
        emoji: '🥂',
        category: 'Evening Afterparty',
        deciderType: 'voting',
        description: 'Post-beach sunset cocktails, music, and celebration at Skylight Rooftop.',
        location: 'Skylight Rooftop Restaurant & Bar',
        time: '07:30 PM - Late',
        estimatedCost: 'Optional / Pay as you order',
        status: 'active',
        isPrimary: false,
      },
    ],
  },
  {
    id: 'board-tarkwa-getaway',
    title: 'Tarkwa Bay Weekend Camping',
    emoji: '🏕️',
    date: 'Oct 03, 2026',
    time: '9:00 AM',
    daysToGo: 18,
    state: 'planning',
    ownerName: 'Tobi',
    description: 'Overnight bonfire, acoustic guitar, camping tents by the shoreline.',
    plans: [
      {
        id: 'plan-tb-1',
        title: 'Shoreline Camping & Bonfire',
        emoji: '🏕️',
        category: 'Main Event',
        deciderType: 'task_duty',
        description: 'Overnight bonfire, acoustic guitar, tents, stargazing, and barbecue.',
        location: 'Tarkwa Bay Shoreline',
        time: '04:00 PM - Next Morning',
        estimatedCost: '₦15,000 / person',
        status: 'active',
        isPrimary: true,
      },
    ],
  },
  {
    id: 'board-lagos-dinner',
    title: 'Lagos Tech Hangout & Suya Night',
    emoji: '🍢',
    date: 'Sept 26, 2026',
    time: '7:30 PM',
    daysToGo: 11,
    state: 'new',
    ownerName: 'Amaka',
    description: 'Casual catchup at Glover Court with 8 developers & founders.',
    plans: [
      {
        id: 'plan-ld-1',
        title: 'Suya Feast & Networking Hangout',
        emoji: '🍢',
        category: 'Main Event',
        deciderType: 'fixed_info',
        description: 'Reserved group table, spicy suya platters, drinks, and casual founder talks.',
        location: 'Glover Court Chops & Bistro',
        time: '07:30 PM - 10:30 PM',
        estimatedCost: '₦7,000 / person',
        status: 'active',
        isPrimary: true,
      },
    ],
  },
];

export const SARAH_WEDDING_BOARD: PlanBoard = {
  id: 'board-sarahs-wedding',
  title: "Sarah' Wedding",
  emoji: '💵',
  coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1600&auto=format&fit=crop&q=80',
  dateTime: '2026-11-20T14:00:00',
  date: 'Fri 20 Nov',
  time: '2:00 PM',
  hasSpecificTime: true,
  daysToGo: 64,
  state: 'planning',
  ownerId: 'user-sarah',
  ownerName: 'Sarah Jenkins',
  description: "Join us in celebrating Sarah and David's wedding! Plan elements, ideas, and schedule together.",
  plans: [
    {
      id: 'sw-plan-venue',
      title: 'Ceremony & Reception Venue',
      emoji: '🏰',
      category: 'Venue',
      deciderType: 'fixed_info',
      description: 'Glasshouse Garden Pavilion with indoor & outdoor reception spaces.',
      location: 'Grand Botanical Glasshouse',
      status: 'confirmed',
      priority: 'required',
    },
    {
      id: 'sw-plan-dress',
      title: 'Color Palette & Dress Code',
      emoji: '🎨',
      category: 'Dress Code',
      deciderType: 'voting',
      description: 'Sage green, champagne, and blush accents for attendees.',
      status: 'active',
      priority: 'required',
    },
    {
      id: 'sw-plan-cocktails',
      title: 'Signature Cocktails',
      emoji: '🍸',
      category: 'Drinks',
      deciderType: 'voting',
      description: 'Vote for the couple cocktail pairing.',
      status: 'active',
      priority: 'optional',
    },
    {
      id: 'sw-plan-cake',
      title: 'Wedding Cake Flavor',
      emoji: '🎂',
      category: 'Cake',
      deciderType: 'photo_idea',
      description: '3-tier botanical floral naked cake.',
      status: 'confirmed',
      priority: 'required',
    },
    {
      id: 'sw-plan-music',
      title: 'First Dance & Playlist',
      emoji: '🎵',
      category: 'Music',
      deciderType: 'photo_idea',
      description: 'Acoustic live strings followed by evening DJ.',
      status: 'active',
      priority: 'important',
    },
    {
      id: 'sw-plan-transport',
      title: 'Guest Shuttle Service',
      emoji: '🚌',
      category: 'Transport',
      deciderType: 'task_duty',
      description: 'Shuttle buses from partner hotels to the venue.',
      status: 'active',
      priority: 'important',
    },
  ],
  members: [
    {
      id: 'user-sarah',
      name: 'Sarah Jenkins',
      role: 'owner',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'user-david',
      name: 'David Jenkins',
      role: 'admin',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'user-seyi',
      name: 'Seyi',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'user-amaka',
      name: 'Amaka',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'user-tobi',
      name: 'Tobi',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'user-kunle',
      name: 'Kunle',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'user-fatima',
      name: 'Fatima',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'user-chinedu',
      name: 'Chinedu',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
  ],
  decisions: [],
  suggestions: [],
  tasks: [],
  contributions: [],
  information: [],
  timeline: [],
  recentActivities: [],
};

